CREATE TABLE "trening" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "naziv" varchar2(50),
  "datum" date
);

CREATE TABLE "vezbe" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ime" varchar2(67) NOT NULL
);

CREATE TABLE "misici" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "naziv" varchar2(50) NOT NULL
);

CREATE TABLE "set" (
  "redni_br" integer,
  "trening_id" integer,
  "vezba_id" integer,
  "kilaza" float,
  "broj_ponavljanja" integer,
  PRIMARY KEY ("redni_br", "trening_id", "vezba_id"),
  PRIMARY KEY ("redni_br", "trening_id", "vezba_id")
);

CREATE TABLE "misici_vezbe" (
  "misici_id" integer,
  "vezbe_id" integer,
  PRIMARY KEY ("misici_id", "vezbe_id")
);

ALTER TABLE "misici_vezbe" ADD FOREIGN KEY ("misici_id") REFERENCES "misici" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "misici_vezbe" ADD FOREIGN KEY ("vezbe_id") REFERENCES "vezbe" ("id") DEFERRABLE INITIALLY IMMEDIATE;


CREATE TABLE "trening_vezbe" (
  "trening_id" integer,
  "vezbe_id" integer,
  PRIMARY KEY ("trening_id", "vezbe_id")
);

ALTER TABLE "trening_vezbe" ADD FOREIGN KEY ("trening_id") REFERENCES "trening" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trening_vezbe" ADD FOREIGN KEY ("vezbe_id") REFERENCES "vezbe" ("id") DEFERRABLE INITIALLY IMMEDIATE;


ALTER TABLE "trening" ADD FOREIGN KEY ("id") REFERENCES "set" ("trening_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vezbe" ADD FOREIGN KEY ("id") REFERENCES "set" ("vezba_id") DEFERRABLE INITIALLY IMMEDIATE;
