CREATE TABLE "trening" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "naziv" varchar(50),
  "datum" date
);

CREATE TABLE "vezbe" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ime" varchar(67) NOT NULL
);

CREATE TABLE "misici" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "naziv" varchar(50) NOT NULL
);

CREATE TABLE "trening_set" (
  "redni_br" integer,
  "trening_id" integer,
  "vezba_id" integer,
  "kilaza" float,
  "broj_ponavljanja" integer,
  PRIMARY KEY ("redni_br", "trening_id", "vezba_id")
);

CREATE TABLE "misici_vezbe" (
  "misici_id" integer,
  "vezbe_id" integer,
  PRIMARY KEY ("misici_id", "vezbe_id")
);

ALTER TABLE "misici_vezbe" ADD FOREIGN KEY ("misici_id") REFERENCES "misici" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "misici_vezbe" ADD FOREIGN KEY ("vezbe_id") REFERENCES "vezbe" ("id") DEFERRABLE INITIALLY IMMEDIATE;





ALTER TABLE "trening_set" ADD FOREIGN KEY ("trening_id") REFERENCES "trening" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "trening_set" ADD FOREIGN KEY ("vezba_id") REFERENCES "vezbe" ("id") DEFERRABLE INITIALLY IMMEDIATE;
